### ISSUE TITLE
Have trouble getting started

### ISSUE THREAD

**Issue by patricorgi** [otavioschwanck/tmux-awesome-manager.nvim#3]
Hi, I'm looking for a neovim plugin for tmux, so I can send predefined commands to certain pane/window within my tmux session. I believe this repo is the best candidate! 

However, I have trouble getting started following your README.md. I don't know how "projects" are defined. I saw in the example, you named two projects `api` and `front`. Do they stand for the name of current working directory or the name of a repository you are currently in? I'm currently inside my project directory which is named "ProjectA", how do I define a list of commands for this project?

This plugin also doesn't recognize the pane/window in my current tmux session. I tried adding a keymap

```
vim.keymap.set('v', 'l', tmux.run_wk({ cmd = 'ls', name = 'ls'}), {})
``` 

When I press `vl` inside my tmux session with a lot of windows, nvim simply tells me `Tmux Awesome Manager: No tmux consoles open.`.

**Comment by otavioschwanck** [comment]
> Hi, I'm looking for a neovim plugin for tmux, so I can send predefined commands to certain pane/window within my tmux session. I believe this repo is the best candidate!
> 
> However, I have trouble getting started following your README.md. I don't know how "projects" are defined. I saw in the example, you named two projects `api` and `front`. Do they stand for the name of current working directory or the name of a repository you are currently in? I'm currently inside my project directory which is named "ProjectA", how do I define a list of commands for this project?
> 
> This plugin also doesn't recognize the pane/window in my current tmux session. I tried adding a keymap
> 
> ```
> vim.keymap.set('v', 'l', tmux.run_wk({ cmd = 'ls', name = 'ls'}), {})
> ```
> 
> When I press `vl` inside my tmux session with a lot of windows, nvim simply tells me `Tmux Awesome Manager: No tmux consoles open.`.

Hi,

The per_project_commands executes the commands for the folder name.  If your project folder is ProjectA, you should do something like:

```lua
require("tmux-awesome-manager").setup({
  project_open_as = "separated_session",
  session_name = "Servers",
  per_project_commands = {
    ProjectA = { { cmd = "rails s", name = "rails server" } },
  },
  default_size = "25%",
  use_icon = true,
  open_new_as = "pane",
  visit_first_call = true,
})
```

So, when you are on ProjectA, just run the `:lua require("tmux-awesome-manager").run_project_terms()`, that will open the defined commands.

About the keymap:
vim.keymap.set("v", "l", tmux.run_wk({ cmd = "ls", name = "ls" }), {})

You defined it with run_wk (that defines a keybinding for which_key).  If you want to map using keymap.set, just do:

```lua
      vim.keymap.set("v", "l", tmux.run({ cmd = "ls", name = "ls" }), {})
```

Example of how i define mine:

```lua
      require("telescope").load_extension("tmux-awesome-manager")

      require("tmux-awesome-manager").setup({
        project_open_as = "separated_session",
        session_name = "Servers",
        per_project_commands = {
          api = { { cmd = "rails s", name = "rails server" } },
          dapp = { { cmd = "rm -rf .next; yarn dev", name = "dapp server" } },
          shun = { { cmd = "yarn start:dev", name = "shun server" } },
          ["evm-contracts"] = { { cmd = "bin/brn start", name = "evm-contracts server" } },
        },
        default_size = "25%",
        use_icon = true,
        open_new_as = "pane",
        visit_first_call = true,
      })

      local tmux = require("tmux-awesome-manager.src.term")

      local set = function(key, opts)
        vim.keymap.set("n", key, tmux.run(opts), { silent = true, noremap = true, desc = opts.name })
      end

      set("<leader>rr", { cmd = "rails console", name = "rails console", open_as = "pane", visit_first_call = true })
      set("<leader>oy", { cmd = "yarn install", name = "yarn install", open_as = "pane" })
      set("<leader>os", {
        cmd = "~/.sync-config.sh",
        name = "sync dotfiles",
        open_as = "pane",
        close_on_timer = 2,
        visit_first_call = false,
      })
      vim.keymap.set("n", "<leader>#", function()
        require("tmux-awesome-manager").run_project_terms()
      end, { silent = true, noremap = true, desc = "Run Project Terms" })

      set("<leader>obC", { cmd = "brownie compile", name = "Brownie Compile", open_as = "pane" })
     ...rest of commands
     ```

**Comment by patricorgi** [comment]
Thanks for the explanation! May I ask which command you use to open a "telescope" like dropped down window allowing to select from a list of items? This was shown in the Demonstration gif. I thought it is via `run_project_terms`, which however is a table of commands run all at once.

I figure perhaps I should describe what I need in my workflow. In my project directory, I typically need to run several `make` commands, but they are quite similar as shown below. 

```
make Apple
make Banana
make Watermelon
make etc.
```

Within tmux, I usually start with a single pane which is of course nvim, and when I run any of the above commands, I would like to create a second pane within the same window to run one of them, say `make Apple`. If later I ran `make Banana`, I want this happends in the same pane as created before. I hope this isn't something too complicated and 'm wondering if it is possible to achieve it using this plugin.

**Comment by otavioschwanck** [comment]
> Thanks for the explanation! May I ask which command you use to open a "telescope" like dropped down window allowing to select from a list of items? This was shown in the Demonstration gif. I thought it is via `run_project_terms`, which however is a table of commands run all at once.
> 
> I figure perhaps I should describe what I need in my workflow. In my project directory, I typically need to run several `make` commands, but they are quite similar as shown below.
> 
> ```
> make Apple
> make Banana
> make Watermelon
> make etc.
> ```
> 
> Within tmux, I usually start with a single pane which is of course nvim, and when I run any of the above commands, I would like to create a second pane within the same window to run one of them, say `make Apple`. If later I ran `make Banana`, I want this happends in the same pane as created before. I hope this isn't something too complicated and 'm wondering if it is possible to achieve it using this plugin.

The uniqueness of the pane could be done using the same name.  You could create a single keybinding to`Make`, but pass an argument, like that:

```lua
      local tmux = require("tmux-awesome-manager.src.term")

      local set = function(key, opts)
        vim.keymap.set("n", key, tmux.run(opts), { silent = true, noremap = true, desc = opts.name })
      end

      set("<leader>m", {
        cmd = "Make",
        name = "make %1",
        open_as = "pane",
        close_on_timer = 0, -- will not close automatically
        visit_first_call = false, -- will not focus the pane
        focus_when_call = false, -- Instead of focusing, will open a new pane in the same place as before
        questions = {
          {
            question = "Make Argument: ",
            required = true,
          },
        },
      })
```

(Also, found a bug while testing this, fixed at: https://github.com/otavioschwanck/tmux-awesome-manager.nvim/commit/214dc6925605f4c42e2648ee99b4e08959c8c6ab, please upgrade XD)

EDIT: 
i added a new feature here: https://github.com/otavioschwanck/tmux-awesome-manager.nvim/commit/8f4e997630a54e557a38a92cec8eca48e8810050

Just set all commands with same pane_id and the new commands pane will replace old ones:
```lua
      set("<leader>mb", {
        cmd = "Make banana",
        name = "Make banana",
        visit_first_call = false,
        focus_when_call = false,
        pane_id = "make",
      })

      set("<leader>ma", {
        cmd = "Make apple",
        name = "Make apple",
        pane_id = "make",
        visit_first_call = false,
        focus_when_call = false,
      })
```

**Comment by otavioschwanck** [comment]
To list commands on dropdown:

vim.keymap.set('n', 'lf', function() vim.cmd(":Telescope tmux-awesome-manager list_terms") end, {}) -- List all terminals

(You Need to map the keybindings first to appear on the list)

**Comment by patricorgi** [comment]
Thank you so much! I'm able to achieve what I want in my workflow in a relatively elegant way now!

**Comment by patricorgi** [comment]
It seems to me `list_terms` only list terms with a key mapping. I actually prefer calling these terms from the drop-down telescope. Assigning individual key mappings for all the terms seems to be redundant to me. Sorry, I have asked for a lot, but I'm wondering if it is possible to make the key maps optional. 

I tried the following. 

```lua
set(nil, {
  cmd = "Make apple",
  name = "Make apple",
  pane_id = "make",
  visit_first_call = false,
  focus_when_call = false,
})
```

It works, but each time I call `list_terms` vim will display an error. 

```
 | lazy.nvim:  | lazy.nvim:  | lazy.nvim: Failed to run `config` for tmux-awesome-manager.nvim

vim/keymap.lua:0: lhs: expected string, got nil

# stacktrace:
  - vim/shared.lua:0 _in_ **validate**
  - vim/keymap.lua:0 _in_ **set**
  - ~/.config/nvim/lua/user/plugins/user.lua:26 _in_ **set**
  - ~/.config/nvim/lua/user/plugins/user.lua:29 _in_ **config**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:8 _in_ **load_extension**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:17 _in_ **__index**
  - /telescope.nvim/lua/telescope/command.lua:183 _in_ **run_command**
  - /telescope.nvim/lua/telescope/command.lua:259 _in_ **load_command**
  - /telescope.nvim/plugin/telescope.lua:108
```

**Comment by otavioschwanck** [comment]
> It seems to me `list_terms` only list terms with a key mapping. I actually prefer calling these terms from the drop-down telescope. Assigning individual key mappings for all the terms seems to be redundant to me. Sorry, I have asked for a lot, but I'm wondering if it is possible to make the key maps optional.
> 
> I tried the following.
> 
> ```lua
> set(nil, {
>   cmd = "Make apple",
>   name = "Make apple",
>   pane_id = "make",
>   visit_first_call = false,
>   focus_when_call = false,
> })
> ```
> 
> It works, but each time I call `list_terms` vim will display an error.
> 
> ```
>  | lazy.nvim:  | lazy.nvim:  | lazy.nvim: Failed to run `config` for tmux-awesome-manager.nvim
> 
> vim/keymap.lua:0: lhs: expected string, got nil
> 
> # stacktrace:
>   - vim/shared.lua:0 _in_ **validate**
>   - vim/keymap.lua:0 _in_ **set**
>   - ~/.config/nvim/lua/user/plugins/user.lua:26 _in_ **set**
>   - ~/.config/nvim/lua/user/plugins/user.lua:29 _in_ **config**
>   - /telescope.nvim/lua/telescope/_extensions/init.lua:8 _in_ **load_extension**
>   - /telescope.nvim/lua/telescope/_extensions/init.lua:17 _in_ **__index**
>   - /telescope.nvim/lua/telescope/command.lua:183 _in_ **run_command**
>   - /telescope.nvim/lua/telescope/command.lua:259 _in_ **load_command**
>   - /telescope.nvim/plugin/telescope.lua:108
> ```

the tmux.run command do two things:
- add the command to the list of commands
- return a function to me mapped.

You can just ignore the second thing, doing this:

```lua
      local tmux = require("tmux-awesome-manager.src.term")

     tmux.run(
          {
            cmd = "Make apple",
            name = "Make apple",
            pane_id = "make",
            visit_first_call = false,
            focus_when_call = false,
          }
    )

     tmux.run(
          {
            cmd = "Make banana",
            name = "Make banana",
            pane_id = "make",
            visit_first_call = false,
            focus_when_call = false,
          }
    )
```

Or a more elegant way:

```lua
    local tmux = require("tmux-awesome-manager.src.term")

    local function map(cmd, name, pane_id, visit_first_call, focus_when_call)
      tmux.run({ cmd = cmd, name = name, pane_id = pane_id, visit_first_call = visit_first_call or false, focus_when_call = focus_when_call or false })
    end

    map("Make banana", 'Run make banana', "make")
    map("Make apple", 'Run make apple', "make")

```

**Comment by patricorgi** [comment]
Thanks a lot!
